### ISSUE TITLE
Incorrect path for data import in Chapter 1

### ISSUE THREAD

**Issue by jgoerner** [PacktWorkshops/Data-Visualization-with-Python#1]
#### Description
The import of dataset fails for a lot of provided notebooks in chapter 1 (`OSError`in case of numpy usage, `FileNotFoundError` in case of pandas usage). This is due to the fact, that the affected notebooks refer to the data as if it would reside in the same directory like in [Exercise1.01](https://github.com/PacktWorkshops/Data-Visualization-with-Python/blob/73569514d82b394894914e491db79b85011f2c53/Chapter01/Exercise1.01/Exercise1.01.ipynb#L50)): 

`dataset = np.genfromtxt('./Datasets/normal_distribution.csv' ... )` 

#### Proposed Solution
Adjust the relative path for file imports like already done in [Exercise1.02](https://github.com/PacktWorkshops/Data-Visualization-with-Python/blob/73569514d82b394894914e491db79b85011f2c53/Chapter01/Exercise1.02/Exercise1.02.ipynb#L44) to 

`dataset = np.genfromtxt('../../Datasets/normal_distribution.csv' ... )` 

#### Tasks
- [x] fix  [Activity 1.01](https://github.com/PacktWorkshops/Data-Visualization-with-Python/blob/master/Chapter01/Activity1.01/Activity1.01.ipynb)
- [x] fix [Activity 1.02](https://github.com/PacktWorkshops/Data-Visualization-with-Python/blob/master/Chapter01/Activity1.02/Activity1.02.ipynb)
- [x] fix [Exercise 1.01](https://github.com/PacktWorkshops/Data-Visualization-with-Python/blob/master/Chapter01/Exercise1.01/Exercise1.01.ipynb)
- [x] fix [Exercise 1.03](https://github.com/PacktWorkshops/Data-Visualization-with-Python/blob/master/Chapter01/Exercise1.03/Exercise1.03.ipynb)
- [x] fix [Exercise 1.04](https://github.com/PacktWorkshops/Data-Visualization-with-Python/blob/master/Chapter01/Exercise1.04/Exercise1.04.ipynb)
- [x] fix [Exercise 1.05](https://github.com/PacktWorkshops/Data-Visualization-with-Python/blob/master/Chapter01/Exercise1.05/Exercise1.05.ipynb)
- [x] fix [Exercise 1.06](https://github.com/PacktWorkshops/Data-Visualization-with-Python/blob/master/Chapter01/Exercise1.06/Exercise1.06.ipynb)
- [x] fix [Exercise 1.07](https://github.com/PacktWorkshops/Data-Visualization-with-Python/blob/master/Chapter01/Exercise1.07/Exercise1.07.ipynb)
